name: Publish Package

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'Enter the new version number'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install twine
    - name: Update version number
      env:
        PACKAGE_NAME: mypackage
        NEW_VERSION: ${{ github.event.inputs.new_version }}
      run : sed -i "s/__version__ = \".*\"/__version__ = \"$package_version\"/" pkgUdit/__init__.py

    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Publish package
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload --skip-existing dist/*