name: Publish to PyPI on Push

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Package Version
        id: get_version
        run: |
          # Retrieve the input value of 'new_version'
          new_version="${{ github.event.inputs.new_version }}"

          # Update the version in the __init__.py file
          sed -i "s/__version__ = \".*\"/__version__ = \"$new_version\"/" pkgUdit/__init__.py

          # Commit the changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -a -m "Update version to $new_version"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install setuptools wheel twine

      - name: Build distribution
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        if: ${{ success() }}
        run: python -m twine upload --skip-existing dist/*

        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
