name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install setuptools wheel twine

      - name: Upgrade version and publish to PyPI
        run: |
          # Increment package version in setup.py
          current_version=$(grep -oP "__version__ = '\K[^']*" setup.py)
          major=$(echo $current_version | cut -d '.' -f 1)
          minor=$(echo $current_version | cut -d '.' -f 2)
          patch=$(echo $current_version | cut -d '.' -f 3)
          new_version="$major.$minor.$((patch + 1))"
          sed -i "s/__version__ = '$current_version'/__version__ = '$new_version'/" setup.py
          python setup.py sdist bdist_wheel
          python -m twine upload --skip-existing --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*

        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
